### PR TITLE
Fix `.grid` margins

### PR DESCRIPTION
**Pull request by oddvalue**

### CODE REVIEW

**Comment by mikestreety** [comment]
I don't think you need anything, it's only if you're concatenating your variable onto another string, or need it in an equation should you need the `#{ }`. Try without anything and see if that works

**Comment by oddvalue** [comment]
Without anything doesn't work. Only reason the `#{ }` is there is because I tried a few things before settling on that.

**Comment by joaoeaugusto** [comment]
Here's an example: http://sassmeister.com/gist/da0883e5ea1d1226cdf9

**Comment by oddvalue** [comment]
Might just be the ancient version of the sass compiler we're using =(

**Comment by mikestreety** [comment]
What are you using in your gulp file? `node-sass` or `sass`?

**Comment by oddvalue** [comment]
`gulp-sass`

**Comment by mikestreety** [comment]
Hmm me to - you up to date with it?

**Pull request merged**
